/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package com.elastic.aisearch.queryUnit;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int READING_TIME = 6;
  /** RegularExpression Id. */
  int CREATED_AT = 7;
  /** RegularExpression Id. */
  int IN_CONTENT = 8;
  /** RegularExpression Id. */
  int IN_TITLE = 9;
  /** RegularExpression Id. */
  int NOT_IN_TITLE = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int NEGATED_QUOTED = 13;
  /** RegularExpression Id. */
  int NEGATED_WORD = 14;
  /** RegularExpression Id. */
  int RANGE_DOTS = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int DATE = 17;
  /** RegularExpression Id. */
  int WORD = 18;
  /** RegularExpression Id. */
  int QUOTED = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"OR\"",
    "\"reading_time:\"",
    "\"created_at:\"",
    "\"in_content:\"",
    "\"in_title:\"",
    "\"-in_title:\"",
    "\">\"",
    "\"<\"",
    "<NEGATED_QUOTED>",
    "<NEGATED_WORD>",
    "\"..\"",
    "<NUMBER>",
    "<DATE>",
    "<WORD>",
    "<QUOTED>",
  };

}
