/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package com.elastic.aisearch.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int READING_TIME = 5;
  /** RegularExpression Id. */
  int CREATED_AT = 6;
  /** RegularExpression Id. */
  int IN_CONTENT = 7;
  /** RegularExpression Id. */
  int IN_TITLE = 8;
  /** RegularExpression Id. */
  int NOT_IN_TITLE = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int NEGATED_QUOTED = 11;
  /** RegularExpression Id. */
  int QUOTED = 12;
  /** RegularExpression Id. */
  int NEGATED_WORD = 13;
  /** RegularExpression Id. */
  int WORD = 14;
  /** RegularExpression Id. */
  int GT = 15;
  /** RegularExpression Id. */
  int LT = 16;
  /** RegularExpression Id. */
  int RANGE_DOTS = 17;
  /** RegularExpression Id. */
  int DATE = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int FILTER_QUOTED = 20;
  /** RegularExpression Id. */
  int FILTER_WORD = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int FILTER_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"reading_time:\"",
    "\"created_at:\"",
    "\"in_content:\"",
    "\"in_title:\"",
    "\"-in_title:\"",
    "\"OR\"",
    "<NEGATED_QUOTED>",
    "<QUOTED>",
    "<NEGATED_WORD>",
    "<WORD>",
    "\">\"",
    "\"<\"",
    "\"..\"",
    "<DATE>",
    "<NUMBER>",
    "<FILTER_QUOTED>",
    "<FILTER_WORD>",
  };

}
